import type {
  Area,
  Organization,
  Project,
  ResourceItem,
  SiteStat,
  StatePresence,
  Story,
  Partner,
} from './types';
import { stateNameToCode } from './geo';

/**
 * Seed content shown when no Supabase connection is configured, so the site
 * is always viewable. Numbers stay blank (—) rather than invented.
 */
export const demoProjects: Project[] = [
  {
    id: 'demo-1',
    slug: 'اعمار-المدارس',
    name_ar: 'إعمار المدارس',
    name_en: 'School Rehabilitation',
    state_code: stateNameToCode('الخرطوم'),
    locality: '',
    areas: ['التعليم'],
    status: 'completed',
    start_date: null,
    end_date: null,
    duration_months: null,
    description_ar: 'إعادة بناء وتأهيل المدارس المتضررة وتوفير بيئة تعليمية آمنة.',
    description_en: '',
    objective_ar: 'العودة الآمنة للطلاب إلى مقاعد الدراسة في مدارس مؤهلة.',
    challenge_ar: 'الضرر الواسع في البنية المدرسية وتشتت الطلاب.',
    activities_ar: 'تأهيل المباني المدرسية، صيانة الفصول، توفير مستلزمات التعليم.',
    results_ar: '',
    impact_ar: 'قيد التوثيق.',
    beneficiaries: 0,
    communities: 0,
    volunteers: 0,
    schools: 0,
    partners: [],
    cover_url: '',
    gallery: [],
    documents: [],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-2',
    slug: 'شباب-من-أجل-التعليم',
    name_ar: 'شباب من أجل التعليم',
    name_en: 'Youth for Education',
    state_code: stateNameToCode('الخرطوم'),
    locality: '',
    areas: ['الشباب', 'التعليم'],
    status: 'planned',
    start_date: null,
    end_date: null,
    duration_months: null,
    description_ar: 'مبادرة تعليمية يقودها الشباب لدعم تعليم أقرانهم.',
    description_en: '',
    objective_ar: 'تمكين الشباب من القيام بدور قيادي في العملية التعليمية.',
    challenge_ar: 'فجوة تعليمية تتفاقم مع محدودية فرص الدعم من الأقران.',
    activities_ar: 'جلسات دعم، توجيه أكاديمي، إشراك متطوعين شباب.',
    results_ar: '',
    impact_ar: 'قيد التوثيق.',
    beneficiaries: 0,
    communities: 0,
    volunteers: 0,
    schools: 0,
    partners: [],
    cover_url: '',
    gallery: [],
    documents: [],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-3',
    slug: 'التدريب-الحرفي-للشباب',
    name_ar: 'التدريب الحرفي للشباب',
    name_en: 'Vocational Training for Youth',
    state_code: stateNameToCode('الجزيرة'),
    locality: '',
    areas: ['الشباب'],
    status: 'planned',
    start_date: null,
    end_date: null,
    duration_months: null,
    description_ar: 'برامج تدريب حرفي ومهني لتمكين الشباب اقتصادياً.',
    description_en: '',
    objective_ar: 'إكساب الشباب مهارات حرفية تولّد فرص عمل ومداخيل.',
    challenge_ar: 'بطالة مرتفعة بين الشباب ومحدودية المهارات الحرفية.',
    activities_ar: 'ورش حرفية، تدريب مهني، إرشاد مهني.',
    results_ar: '',
    impact_ar: 'قيد التوثيق.',
    beneficiaries: 0,
    communities: 0,
    volunteers: 0,
    schools: 0,
    partners: [],
    cover_url: '',
    gallery: [],
    documents: [],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-4',
    slug: 'التعافي-والدعم-النفسي',
    name_ar: 'التعافي والدعم النفسي',
    name_en: 'Recovery & Psychosocial Support',
    state_code: stateNameToCode('شمال دارفور'),
    locality: '',
    areas: ['تقوية روابط المجتمع'],
    status: 'planned',
    start_date: null,
    end_date: null,
    duration_months: null,
    description_ar: 'دعم نفسي واجتماعي مجتمعي بعد الأزمات.',
    description_en: '',
    objective_ar: 'مساعدة المجتمعات على التعافي وتماسك روابطها.',
    challenge_ar: 'آثار نفسية واجتماعية عميقة خلفتها الأزمة على المجتمعات.',
    activities_ar: 'جلسات دعم نفسي، أنشطة مجتمعية، متابعة أسرية.',
    results_ar: '',
    impact_ar: 'قيد التوثيق.',
    beneficiaries: 0,
    communities: 0,
    volunteers: 0,
    schools: 0,
    partners: [],
    cover_url: '',
    gallery: [],
    documents: [],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const demoStories: Story[] = [
  {
    id: 'demo-s1',
    type: 'story',
    title_ar: 'العودة إلى الفصل في الخرطوم',
    title_en: '',
    body_ar: 'قصة ميدانية طويلة تتناول رحلة طلاب إعادة تأهيل مدارسهم بعد الأضرار، تُستكمل بالبيانات الفعلية من الفريق الميداني.',
    author: '',
    project_slug: 'اعمار-المدارس',
    image_url: '',
    images: [],
    state_code: stateNameToCode('الخرطوم'),
    published_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-s2',
    type: 'news',
    title_ar: 'تدريب متطوعين شباب في الجزيرة',
    title_en: '',
    body_ar: 'إشارة قصيرة لتغطية تُستكمل لاحقاً.',
    author: '',
    project_slug: 'التدريب-الحرفي-للشباب',
    image_url: '',
    images: [],
    state_code: stateNameToCode('الجزيرة'),
    published_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-s3',
    type: 'story',
    title_ar: 'جلسات تعافٍ في شمال دارفور',
    title_en: '',
    body_ar: 'تغطيةٌ ميدانية لأنشطة الدعم النفسي المجتمعي تُستكمل بالبيانات والصور.',
    author: '',
    project_slug: 'التعافي-والدعم-النفسي',
    image_url: '',
    images: [],
    state_code: stateNameToCode('شمال دارفور'),
    published_at: '2026-01-01T00:00:00Z',
  },
];
export const demoResources: ResourceItem[] = [];
export const demoPartners: Partner[] = [];

export const demoAreas: Area[] = [
  {
    id: 'demo-a1',
    slug: 'youth',
    name_ar: 'الشباب',
    name_en: 'Youth',
    description_ar: 'تمكين اقتصادي وتعليمي وقيادي للشباب.',
    description_en: '',
    cover_image: '',
    sort_order: 1,
  },
  {
    id: 'demo-a2',
    slug: 'community',
    name_ar: 'تقوية روابط المجتمع',
    name_en: 'Community Social Cohesion',
    description_ar: 'دعم التماسك الاجتماعي والاستجابة المجتمعية في الأزمات.',
    description_en: '',
    cover_image: '',
    sort_order: 2,
  },
  {
    id: 'demo-a3',
    slug: 'education',
    name_ar: 'التعليم',
    name_en: 'Education',
    description_ar: 'حماية التعليم وضمان استمراريته في البيئات الهشة.',
    description_en: '',
    cover_image: '',
    sort_order: 3,
  },
];

export const demoOrganization: Organization = {
  id: 1,
  name_ar: 'منظمة العمل الإنساني والتنمية المستدامة',
  name_en: 'HASDO',
  acronym: 'HASDO',
  description_ar: 'عمل إنساني يبدأ من الإنسان، والتنمية تبدأ من المجتمع.',
  mission_ar: '',
  vision_ar: '',
  logo_url: '',
  email: '',
  phone: '',
  address_ar: 'المقر: السودان',
  social_links: [],
};

/** حضور تجريبي للخريطة: مقر رئيسي واحد في الخرطوم، والبقية مواقع عمل
 * بلا مكاتب دائمة (دائرة مفرغة). */
export function demoPresence(): StatePresence[] {
  const khartoum = stateNameToCode('الخرطوم');
  const jazirah = stateNameToCode('الجزيرة');
  const nDarfur = stateNameToCode('شمال دارفور');
  return [
    ...(khartoum ? [{ code: khartoum, office_kind: 'country' as const }] : []),
    ...(jazirah ? [{ code: jazirah, office_kind: null }] : []),
    ...(nDarfur ? [{ code: nDarfur, office_kind: null }] : []),
  ];
}
export const demoStats: SiteStat[] = [
  { key: 'beneficiaries', label_ar: 'شخص تم الوصول إليهم', value_num: 0, value: '' },
  { key: 'projects', label_ar: 'مشروعاً منفذاً', value_num: 0, value: '' },
  { key: 'communities', label_ar: 'مجتمعات', value_num: 0, value: '' },
  { key: 'states', label_ar: 'ولايات', value_num: 0, value: '' },
  { key: 'volunteers', label_ar: 'متطوع', value_num: 0, value: '' },
];